# --- 1. SPAZIO DISCO (PERSISTENZA) ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# --- 2. DEPLOYMENT (IL SERVER DATABASE) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgis/postgis:15-3.4-alpine
        ports:
        - containerPort: 5432
        
        env:

        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets       # Il nome del file Secret
              key: postgres-password  # Il nome della riga da pescare
        
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data 
          subPath: postgres-data 

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
# --- 3. SERVIZIO DI RETE INTERNO ---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service 
  namespace: default
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP