apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  # --- 1. CHIAVI DI SICUREZZA ---
  jwt-secret: "super-secret-key-assetmanagement-2026"
  
  # --- 2. CREDENZIALI ROOT INFRASTRUTTURA (Per i Deployment DB) ---
  postgres-password: "password_super_sicura"
  
  mongo-root-user: "mongo_admin"
  mongo-root-password: "password_super_sicura"
  
  minio-root-user: "admin_minio"
  minio-root-password: "password_super_sicura"
  
  rabbitmq-user: "admin_mq"
  rabbitmq-password: "password_super_sicura"

  # --- 3. STRINGHE DI CONNESSIONE ---
  # PostgreSQL (I 5 database logici)
  auth-db-url: "postgresql://postgres:password_super_sicura@postgres-service:5432/auth_db"
  geo-db-url: "postgresql://postgres:password_super_sicura@postgres-service:5432/geo_db"
  warning-db-url: "postgresql://postgres:password_super_sicura@postgres-service:5432/warning_db"
  log-db-url: "postgresql://postgres:password_super_sicura@postgres-service:5432/log_db"
  media-db-url: "postgresql://postgres:password_super_sicura@postgres-service:5432/media_db"
  
  # Altri Storage
  asset-db-url: "mongodb://mongo_admin:password_super_sicura@mongodb-service:27017/asset_db?authSource=admin"
  rabbitmq-url: "amqp://admin_mq:password_super_sicura@rabbitmq-service:5672"
  minio-endpoint: "minio-service:9000"

