apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-deployment
  namespace: default
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
      - name: media-service
        image: claudia179/media-service-img:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        
        # --- CONFIGURAZIONE AMBIENTE ---
        env:
        - name: PORT
          value: "5000"
        
        # 1. URL DEL DATABASE RELAZIONALE LEGGERO (PostgreSQL - media_db per i metadati dei file)
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: media-db-url
        
        # 2. CHIAVE DI SICUREZZA JWT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret

        # 3. CONFIGURAZIONE OBJECT STORAGE (MinIO / S3)
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: minio-endpoint
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: minio-root-user
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: minio-root-password
        - name: MEDIA_BUCKET
          value: "media-bucket"
          
        # 4. COLLEGAMENTO AL MESSAGE BROKER 
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: rabbitmq-url

        # 5. CREDENZIALI GOOGLE CLOUD VISION (IA)
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/gcp/credentials.json"

        # MONTAGGIO DEL FILE FISICO DELLE CREDENZIALI NEL CONTAINER
        volumeMounts:
        - name: gcp-credentials
          mountPath: "/etc/gcp"
          readOnly: true

      # DEFINIZIONE DEL VOLUME CHE LEGGE IL SECRET DA KUBERNETES
      volumes:
      - name: gcp-credentials
        secret:
          secretName: gcp-secret

---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: default
spec:
  selector:
    app: media-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP